# action.yml
name: 'Compile with Therion'
description: 'Compile a therion based project'

inputs:
  thconfig:  # id of input
    description: 'thconfig file path'
    required: true
runs:
  using: 'docker'
  image: 'docker://matteopic/therion:6.1.8'
  args:
    - ${{ inputs.thconfig }}